---
title: SAR Research
execute:
    echo: false
---

Synthetic Aperture RADAR or SAR is a powerful tool for interrogating the physical properties of Earth's surface. By illuminating a swath of the planet's surface with RADAR waves of given intensity, polarization state, and frequency and carefully considering the returned wave, we can make nuanced arguments about what type and arrangement of matter it scattered off of. This is commonly used to extract a wide bevy of environmental information including snow mass, vegetation density, and soil moisture. Unlike visible light RADAR wavelengths penetrate deep into many materials, having complex interactions throughout the body of the target and ignoring complications like clouds completely.

In my opinion SAR research is entering a stage of increased productivity and promise with the launch of more advanced instruments including RCM, NISAR, and various bespoke airborne instruments like the UW CryoSAR. With quad- and compact- polarized options improving, more nuanced polarimetric analysis of targets becomes possible. With revisit times increasing, interferometric analyses become more coherent (literally). And with more observations at more irradiation wavelengths being collected, interesting multi-instrument investigations start to become practical.

My research largely focuses on SAR polarimetry, SAR interferometry, and radiative transfer modelling of snow and lake ice. I'm interested in both developing some theoretical questions (e.g. in what regimes are different scattering mechanisms dominant in these systems?) and operationally-minded products (e.g. can we extract ice growth rate bounds using an interferometric approach?).